package com.poc.firebase;

import org.apache.camel.Endpoint;
import org.apache.camel.test.junit4.CamelTestSupport;
import org.junit.Test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

public class FirebaseFirestoreAdapterComponentComponentTest
        extends CamelTestSupport {

    @Test
    public void testFirebaseEndpointConfiguration() throws Exception {

        Endpoint endpoint = context.getEndpoint(
                "firebase-firestore://foo"
                        + "?projectId=cpi-custom-adapter-poc"
                        + "&credentialAlias=firebase-service-account"
                        + "&collection=users"
                        + "&documentId=adapter-component-test-001"
                        + "&operation=CREATE");

        assertTrue(endpoint instanceof FirebaseFirestoreAdapterComponentEndpoint);

        FirebaseFirestoreAdapterComponentEndpoint firestoreEndpoint =
                (FirebaseFirestoreAdapterComponentEndpoint) endpoint;

        assertEquals("cpi-custom-adapter-poc", firestoreEndpoint.getFirebaseProjectId());
        assertEquals("firebase-service-account", firestoreEndpoint.getCredentialAlias());
        assertEquals("users", firestoreEndpoint.getCollection());
        assertEquals("adapter-component-test-001", firestoreEndpoint.getDocumentId());
        assertEquals("CREATE", firestoreEndpoint.getOperation());
    }
    /*
     * NOTE: This test used to assert on the raw pom.xml text, requiring every
     * embedded jar filename to be hand-typed into <Bundle-ClassPath>. That's
     * wrong on two counts: (1) it's brittle — any dependency version bump
     * breaks it even though nothing is actually wrong, and (2) the real OSGi
     * manifest is only generated by maven-bundle-plugin during the `package`
     * phase, which runs *after* this `test` phase — so no unit test here can
     * meaningfully validate the shipped Bundle-ClassPath anyway.
     *
     * The actual regression this was trying to catch (a literal "lib/*.jar"
     * wildcard in the built manifest, which Equinox does not expand) is
     * covered by Embed-Dependency/Embed-Transitive in the pom, and should be
     * verified post-package, e.g. by unzipping target/build/*.esa in CI and
     * grepping the inner jar's META-INF/MANIFEST.MF for "Bundle-ClassPath:"
     * to confirm it lists explicit jar names and not a wildcard.
     */
}