import React, { useState, useEffect } from 'react';
import { Sliders, ArrowRight, ArrowLeft, Info, Key, Brain, Cpu, CheckCircle } from 'lucide-react';

/**
 * Step 2 — AI-Generated Technology Parameters
 *
 * This form renders EXACTLY what Claude AI returned — no hardcoded fields.
 * If AI says Cassandra needs: contactPoints, keyspace, tableName, credentialAlias → those fields appear.
 * If AI says Firebase needs: projectId, collectionPath, credentialAlias → those appear.
 * The user can review/edit values before proceeding.
 */
export default function DynamicTechForm({ parsedResult, onNext, onPrev }) {
  const spec  = parsedResult?.specification;
  const tech  = parsedResult?.technology;
  const aiEngine = parsedResult?.aiEngine || '';
  const summary  = parsedResult?.parsedPromptSummary || '';

  const [formParams, setFormParams] = useState({});

  useEffect(() => {
    if (spec?.connection?.parameters) {
      const initial = {};
      spec.connection.parameters.forEach((p) => {
        initial[p.name] = p.defaultValue || '';
      });
      setFormParams(initial);
    }
  }, [spec]);

  const handleChange = (name, value) => {
    setFormParams((prev) => ({ ...prev, [name]: value }));
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    const updatedParams = spec.connection.parameters.map((p) => ({
      ...p,
      defaultValue: formParams[p.name] !== undefined ? formParams[p.name] : p.defaultValue
    }));
    const updatedSpec = {
      ...spec,
      connection: { ...spec.connection, parameters: updatedParams }
    };
    onNext(updatedSpec);
  };

  if (!spec) {
    return (
      <div className="glass-panel" style={{ padding: '32px', textAlign: 'center' }}>
        <p style={{ color: 'var(--text-secondary)' }}>Please complete Step 1 first.</p>
        <button className="btn-secondary" onClick={onPrev} style={{ marginTop: '16px' }}>
          <ArrowLeft size={16} /> Back to Step 1
        </button>
      </div>
    );
  }

  const isAiGenerated = aiEngine.includes('Claude');
  const direction = spec.adapter?.direction || 'receiver';
  const targetSystem = tech?.displayName || spec.target?.technology || 'Target System';
  const category = spec.target?.category || '';
  const authType = spec.authentication?.type || '';
  const credAlias = formParams['credentialAlias'] || formParams['credential_alias'] || 'SAP_SECURE_ALIAS';

  return (
    <div className="glass-panel" style={{ padding: '32px' }}>

      {/* Header */}
      <div style={{ marginBottom: '24px' }}>
        <h2 style={{ fontSize: '18px', fontWeight: '700', marginBottom: '8px', display: 'flex', alignItems: 'center', gap: '10px' }}>
          <Sliders size={20} color="#2563eb" />
          Step 2 — AI-Generated Connection Parameters
        </h2>
        <p style={{ fontSize: '13.5px', color: 'var(--text-secondary)', lineHeight: '1.6' }}>
          These fields were generated by Claude AI based on your description of <strong>{targetSystem}</strong>.
          Review and adjust values as needed.
        </p>
      </div>

      {/* AI Summary Banner */}
      <div style={{
        padding: '14px 18px', borderRadius: '10px', marginBottom: '24px',
        background: isAiGenerated ? 'linear-gradient(135deg, #eff6ff, #f5f3ff)' : '#fefce8',
        border: `1px solid ${isAiGenerated ? '#bfdbfe' : '#fde68a'}`,
        display: 'flex', alignItems: 'flex-start', gap: '12px'
      }}>
        {isAiGenerated ? <Brain size={18} color="#2563eb" style={{ marginTop: '1px', flexShrink: 0 }} /> : <Cpu size={18} color="#d97706" style={{ marginTop: '1px', flexShrink: 0 }} />}
        <div>
          <div style={{ fontSize: '12.5px', fontWeight: '600', color: isAiGenerated ? '#1d4ed8' : '#92400e', marginBottom: '3px' }}>
            {aiEngine}
          </div>
          <div style={{ fontSize: '12.5px', color: isAiGenerated ? '#3730a3' : '#78350f', lineHeight: '1.5' }}>
            {summary}
          </div>
        </div>
      </div>

      {/* Target System Card */}
      <div className="glass-card" style={{
        padding: '18px', marginBottom: '24px',
        background: '#eff6ff', borderColor: '#bfdbfe',
        display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '12px'
      }}>
        <div>
          <div style={{ fontWeight: '700', fontSize: '16px', color: '#1d4ed8', marginBottom: '4px' }}>
            {targetSystem}
          </div>
          <div style={{ fontSize: '12.5px', color: '#3730a3' }}>
            {category && <span style={{ marginRight: '12px' }}>Category: <strong>{category}</strong></span>}
            {authType && <span>Auth: <strong>{authType}</strong></span>}
          </div>
        </div>
        <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
          <span className="badge badge-purple" style={{ fontSize: '11px' }}>
            {direction.toUpperCase()} DIRECTION
          </span>
          {spec.adapter?.scheme && (
            <span className="badge badge-blue" style={{ fontSize: '11px' }}>
              scheme: {spec.adapter.scheme}
            </span>
          )}
        </div>
      </div>

      <form onSubmit={handleSubmit}>

        {/* AI-generated connection parameters */}
        {spec.connection?.parameters?.length > 0 ? (
          <>
            <div style={{ fontSize: '13px', fontWeight: '600', color: 'var(--text-secondary)', marginBottom: '12px', letterSpacing: '0.5px', textTransform: 'uppercase' }}>
              Connection Parameters ({spec.connection.parameters.length} fields generated by AI)
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '16px', marginBottom: '24px' }}>
              {spec.connection.parameters.map((param) => (
                <div key={param.name} className="glass-card" style={{ padding: '18px' }}>
                  <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: '8px', gap: '8px' }}>
                    <label style={{ fontWeight: '600', fontSize: '13.5px', color: 'var(--text-primary)', lineHeight: '1.3' }}>
                      {param.label || param.name}
                      {param.required && <span style={{ color: '#dc2626', marginLeft: '3px' }}>*</span>}
                    </label>
                    <div style={{ display: 'flex', gap: '5px', flexShrink: 0 }}>
                      <span className="badge badge-blue" style={{ fontSize: '10px' }}>{param.name}</span>
                      {param.type === 'secure-alias' && (
                        <span className="badge" style={{ fontSize: '10px', background: '#fef3c7', color: '#92400e', border: '1px solid #fde68a' }}>🔐 secure</span>
                      )}
                    </div>
                  </div>

                  <input
                    type={param.type === 'integer' ? 'number' : 'text'}
                    value={formParams[param.name] || ''}
                    onChange={(e) => handleChange(param.name, e.target.value)}
                    required={param.required}
                    placeholder={param.defaultValue || `Enter ${param.label || param.name}`}
                    style={{ marginTop: '4px' }}
                  />

                  {param.description && (
                    <p style={{ fontSize: '12px', color: 'var(--text-muted)', marginTop: '7px', display: 'flex', alignItems: 'flex-start', gap: '5px', lineHeight: '1.4' }}>
                      <Info size={12} style={{ flexShrink: 0, marginTop: '1px' }} /> {param.description}
                    </p>
                  )}
                </div>
              ))}
            </div>
          </>
        ) : (
          <div style={{ padding: '20px', background: '#fef9e7', border: '1px solid #fde68a', borderRadius: '8px', marginBottom: '24px', fontSize: '13.5px', color: '#92400e' }}>
            ⚠️ No connection parameters were generated. Go back and refine your description with more detail about the target system.
          </div>
        )}

        {/* Zero Credentials Policy notice */}
        <div className="glass-card" style={{ padding: '14px 18px', marginBottom: '24px', background: '#ecfdf5', borderColor: '#a7f3d0' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '5px' }}>
            <Key size={15} color="#059669" />
            <span style={{ fontSize: '13px', fontWeight: '600', color: '#047857' }}>Zero Raw Credentials Policy</span>
            <CheckCircle size={14} color="#059669" />
          </div>
          <p style={{ fontSize: '12px', color: '#065f46', lineHeight: '1.6', margin: 0 }}>
            Credentials are retrieved at runtime via SAP <code>ITApiFactory.getService(SecureStoreService.class)</code> using alias{' '}
            <code style={{ background: '#d1fae5', padding: '1px 5px', borderRadius: '4px' }}>{credAlias}</code>.{' '}
            No secrets are ever stored in generated code or logs.
          </p>
        </div>

        {/* Operations generated by AI */}
        {spec.operations?.length > 0 && (
          <div style={{ marginBottom: '24px' }}>
            <div style={{ fontSize: '13px', fontWeight: '600', color: 'var(--text-secondary)', marginBottom: '10px', letterSpacing: '0.5px', textTransform: 'uppercase' }}>
              Supported Operations (AI-determined)
            </div>
            <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
              {spec.operations.map((op, i) => (
                <div key={i} style={{
                  padding: '6px 14px', borderRadius: '20px', fontSize: '12.5px', fontWeight: '500',
                  background: op.enabled ? '#eff6ff' : '#f8fafc',
                  color: op.enabled ? '#1d4ed8' : '#9ca3af',
                  border: `1px solid ${op.enabled ? '#bfdbfe' : '#e5e7eb'}`
                }}>
                  {op.enabled && <CheckCircle size={12} style={{ marginRight: '5px', verticalAlign: 'middle' }} />}
                  {op.name}
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Navigation */}
        <div style={{ display: 'flex', justifyContent: 'space-between', paddingTop: '8px' }}>
          <button type="button" className="btn-secondary" onClick={onPrev}>
            <ArrowLeft size={16} /> Back to Requirement
          </button>
          <button type="submit" className="btn-primary" disabled={spec.connection?.parameters?.length === 0}>
            Review Full Specification <ArrowRight size={16} />
          </button>
        </div>
      </form>
    </div>
  );
}
